#Campfire alerting extension required properties

#campfire User name
userName: ""

#campfire password
password: ""

#campfire sub domain
subDomain: "india11"

#roomName to post messages to
roomName: "Room 1"